### ISSUE TITLE
Adding puppeteer stealth

### ISSUE THREAD

**Issue by shipsource** [YusukeIwaki/puppeteer-ruby#102]
### Simple description about the feature

Does this wrapper supports all the puppeteer extra features like stealth?

### Usecase / Motivation

To further conceal Puppeteer activity.

**Comment by YusukeIwaki** [comment]
Thank you for your feature request.
I have no plan to support stealth plugin at this moment.

I know some similar libraries (puppeteer-dart, playwright, ...) already supports the stealth plugin.
However I don't understand when to use the feature actually because most web-pages doesn't distinguish puppeteer's activity.

Also, IMHO, we can easily change User-Agent or other internal implementations dynamically in Ruby, using monkey-patching. So I believe the stealth plugin is rarely needed in puppeteer-ruby.

Could you share the concrete use-case for stealth plugin?
