### ISSUE TITLE
page.set_cookie

### ISSUE THREAD

**Issue by Toucouleur66** [YusukeIwaki/puppeteer-ruby#211]
```
def puppeting(url)
  Puppeteer.launch(
    headless: true,
  ) do |browser|
    page = browser.new_page
    # ap page.methods
    page.viewport = Puppeteer::Viewport.new(width: 1980, height: 1080)
    page.default_navigation_timeout = 0
    page.set_cookie(
      {
        token: "123456",
      }
    )
    wait_until = "domcontentloaded"
    page.goto(url, wait_until: wait_until, timeout: 0)
    page.screenshot(path: "tmp/#{Time.now.to_i}.png")
  end
end

puppeting("https://www.yoursite.com")
```

Return:

```Puppeteer::Connection::ProtocolError (Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.name - BINDINGS: mandatory field missing at position 79)```

**Comment by YusukeIwaki** [comment]
@Toucouleur66 Sorry for late response,

`set_cookie` required a parameter like `{ name: 'token', value: '123456' }` instead of `{ token: '123456' }`.
This parameter spec is ported from the original JS version of Puppeteer. https://github.com/puppeteer/puppeteer/blob/v13.5.2/docs/api.md#pagesetcookiecookies
