### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tchret** [YusukeIwaki/puppeteer-ruby#30]
Hi @YusukeIwaki, this is an amazing wrapper you are building here.
Do you have any public roadmap available so we can see what still needs to be done?

**Comment by YusukeIwaki** [comment]
Currenrly I don't have it because this library is just for my private project at this point.
Howevert I think most Rails developers would be interested in this library. So I will provide the roadmap.

IMHO, just a browser automation or testing can be simply done with rubycdp/ferrum or rubycdp/cuprite. These libraries already have user friendly classes and methods.
The advantage of puppeteer-ruby is the ability of integration into *existing* projects.
`Puppeteer#connect` allows us to use Puppeteer APIs with existing automation scripts. And `Page#waitForSelector` or `Page#waitForNavigation` would helps us to make more reliable test-cases.

So I have no plan to migrate all of the functionality from original Puppeteer into puppeteer-ruby at this point.At first, I want to focus to introduce core functionalities useful for Rails system-testing implementation or existing browser automation maintaining.
